app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

background color changed to alice blue
search bar centered, givers button align to the left

Navbar Searchbar modifications

---

app/views/shared/_navbar.html.erb

Name changed to Find a Giver

---

app/views/pages/home.html.erb

removed button

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

sign up button now redirects to right form

fixed signup

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/shared/_navbar.html.erb

cleanedStyle

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/pages_controller.rb
app/views/pages/search.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

implemented search funtionality 
currently search for users
case insensitive
displays "noresults" when no results are found

search functionality

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

layout in home fixed, added buttons for get help and give help and picture restored

home layout fixed

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

smallsynthaxfix

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

button layout adjusted
added names to dropout menu actions

fixedbuttons

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

buttons linked to the right pages

linked buttons

---

app/controllers/users_controller.rb
app/views/shared/_navbar.html.erb
app/views/users/profile.html.erb
config/routes.rb

added a my profile in the user scrolldown menu which links to a user profile page thata as of now only displays username and email

added a my profile

---

app/controllers/users_controller.rb
app/views/users/edit.html.erb
app/views/users/profile.html.erb
config/routes.rb

editprofile

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

cleanhomepage

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

workinprogress

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/search.html.erb

added a view button to see profile of searched person

provileview

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

a cleaner homepage with correct button names/links

cleanedhomepage

---

app/assets/stylesheets/components/_navbar.scss
app/views/users/new.html.erb

fixed a problem with the buttons shifting

fixedshiftedbuttons

---

app/controllers/requests_controller.rb
app/views/requests/my_requests.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

added a my requests action to scroll down menu with remove request and add request (stillnotworking)

myrequests

---

app/views/shared/_footer.html.erb

Footers simplyfied a quick fix due to feedback

Footers simplyfied

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_requests.scss
app/assets/stylesheets/users/_index.scss
app/controllers/requests_controller.rb
app/views/requests/index.html.erb
app/views/shared/_navbar.html.erb
app/views/users/index.html.erb

implemewnted separate searchbar for requests , still needs styling

Seachbar on page implement

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

added title and description

---

app/assets/stylesheets/components/_requests.scss
app/views/requests/index.html.erb

Request Button fix

---

app/assets/stylesheets/components/_requests.scss
app/controllers/messages_controller.rb
app/models/message.rb
app/models/user.rb
app/views/messages/index.html.erb
app/views/messages/new.html.erb
config/routes.rb
db/migrate/20240311145337_add_content_to_messages.rb
db/migrate/20240311152324_change_messages_request_id_to_null_true.rb
db/schema.rb

implemented simple message form
still need style
and button to acces

basicMessageform

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_messages.scss
app/controllers/messages_controller.rb
app/views/messages/index.html.erb
app/views/messages/new.html.erb
config/routes.rb

added some basic styling for the messages and messages/new

basic message style

---

app/assets/stylesheets/users/_index.scss
app/views/users/profile.html.erb
db/schema.rb
test/models/match_suggestion_test.rb

Edit Profile Button Fixed

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

removed my requests added my messages and added link to dashboard also

scrolldownmenubuttons

---

app/controllers/users_controller.rb

A little change on the user_controller

User Controller Update

---

app/views/devise/registrations/new.html.erb

Username Added

---

app/assets/stylesheets/pages/_messages.scss
app/controllers/messages_controller.rb
app/models/message.rb
app/views/messages/index.html.erb
app/views/messages/new.html.erb

added more functionality to the chat 
you can now select a request when sending a message added some style thjat is coherent with other pages
and added mor info in /messages also separated received and sent in two different containers

addedstyle

---

app/views/shared/_navbar.html.erb
app/views/users/show.html.erb

added a butto in scroll down menu to go to all givers and getters also added a butto to write a message on profiles

added some links

---

app/views/users/index.html.erb
app/views/users/show.html.erb

added pic to profiles

---

app/assets/stylesheets/components/_footer.scss
app/controllers/pages_controller.rb
app/views/pages/privacy.html.erb
app/views/pages/terms.html.erb
app/views/shared/_footer.html.erb
config/routes.rb

Footer reduced
Terms conditions
Privacy added

Footer reduced

---

app/controllers/messages_controller.rb
app/controllers/requests_controller.rb
app/controllers/users_controller.rb
app/views/messages/new.html.erb

Some notices added after completing actions.

Notices Added

---

app/assets/stylesheets/components/_requests.scss
app/assets/stylesheets/users/_index.scss
app/views/requests/index.html.erb
app/views/users/index.html.erb

centered searchbars and headers

centeredstuff

---

app/controllers/requests_controller.rb
app/views/requests/show.html.erb

Match Suggestions fixed, doesn't  picked randomly. Picked all the experts related.

Suggestions Fixed

---

app/views/pages/dashboard.html.erb
app/views/requests/show.html.erb

Also added my request button
Some link added

Links Added to Requests

---

app/assets/stylesheets/pages/_requests.scss
app/views/users/show.html.erb

flow changes
